apiVersion: v1
data:
  rotate-nginx.conf: |+
    /var/log/nginx/access.log  {
    daily
    rotate 7
    missingok
    dateext
    compress
    delaycompress
    notifempty
    sharedscripts
    postrotate
        [ -e /var/log/nginx/nginx.pid ] && kill -USR1 `cat /var/log/nginx/nginx.pid`
    endscript
    }
  nginx.conf: |+

    #user  nobody;
    worker_processes  auto;

    #error_log  /dev/stdout;
    error_log  /var/log/nginx/error.log  error;

    pid        /var/log/nginx/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       mime.types;
        default_type  application/octet-stream;

        log_format  main  '[access] $remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;
        #access_log off;

        sendfile        on;
        #tcp_nopush     on;

        #keepalive_timeout  0;
        keepalive_timeout  65;

        #gzip  on;

        server {
            listen       9000;
            server_name  localhost;

            #charset koi8-r;

            #access_log  logs/host.access.log  main;

            location / {
                root   html;
                index  index.html index.htm;
            }

            location /sleep_10ms {
            echo_sleep 0.01;
            echo sleep10ms;
            }

            location /sleep_20ms {
            echo_sleep 0.02;
            echo sleep20ms;
            }

            #error_page  404              /404.html;

            # redirect server error pages to the static page /50x.html
            #
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   html;
            }
        }
    }
  filebeat.yml: |+
    filebeat.inputs:
      - type: log
        paths:
          - /var/log/nginx/*.log
        close_timeout: 10m
        fields_under_root: true
        fields:
          log_type: "app"
          kubernetes.namespace_name: ${NAMESPACE}
          kubernetes.container_name: ${APP}
          kubernetes.host: ${NODE_NAME}
          kubernetes.pod_id: ${UID}
          kubernetes.pod_name: ${HOSTNAME}

        # Java Exception match
        multiline:
          type: pattern
          pattern: '^[[:space:]]'
          negate: false
          match: after

    output.elasticsearch:
      hosts: ['https://${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      ssl.certificate_authorities: ${FB_CERT_AUTHORITIES}
      ssl.certificate: ${FB_CLIENT_CERT}
      ssl.key: ${FB_CLIENT_KEY}
      indices:
        - index: "app-write"
          when.equals:
            log_type: "app"
        - index: "infra-write"
          when.equals:
            log_type: "infra"
        - index: "audit-write"
          when.equals:
            log_type: "audit"

    setup.template:
      enabled: false
    logging.level: info
kind: ConfigMap
metadata:
  name: sidecar-config
  namespace: ocp-test